[build]
  command = "next build"
  publish = ".next"

[build.environment]
  FRAME_ANCESTORS = "'self' "
  VPS_BACKEND_URL = "http://167-104-101-54.nip.io:3000"

[[plugins]]
  package = "@netlify/plugin-nextjs"
